sudo: false
language: ruby
cache: bundler
matrix:
  include:
  - rvm: jruby-9.1.13.0
  - rvm: jruby-9.1.7.0
  fast_finish: true
install: true
before_script:
  - bundle exec rake vendor
script: 
  - bundle exec rspec spec
jdk: oraclejdk8
